# Generated by Django 4.2.1 on 2024-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pojisteny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jmeno", models.CharField(max_length=100)),
                ("prijmeni", models.CharField(max_length=100)),
                ("vek", models.IntegerField()),
                ("telefon", models.CharField(max_length=15)),
            ],
        ),
    ]
